### PR TITLE
add function to select closest timesteps from a larda container to a …

### PR DESCRIPTION
**Pull request by jroettenbacher**
…given array of timesteps

This is useful, when interpolating is not the way to go. For example when plotting the HATPRO flag together with radar data. The Flag should not be interpolated

Plus some formatting

### CODE REVIEW

**Comment by martin-rdz** [comment]
How is that function different to 
https://github.com/lacros-tropos/larda/blob/29b80f9d045736af26491d351f6bf1c7e73d6822/pyLARDA/Transformations.py#L292
with just being given a single timestep as shown in [slice_container doc](https://lacros-tropos.github.io/larda-doc/html/datacontainer_and_transformation.html#pyLARDA.Transformations.slice_container)?
The range argument can be omitted in slice container, providing the full height interval.

**Comment by jroettenbacher** [comment]
I didn't know about that function. My function is not as sophisticated. We can ignore this pull request then.
Cheers

**Comment by jroettenbacher** [comment]
Sorry, haven't tested it before closing it. So as far as I understand `slice_container` takes slices from timestep1 to timestep2 or just a single timestep. However, I want to select the timesteps from one instrument which are closest to the timesteps to another instrument. 
I tried using the interpolate1d function by adding a keyword kind to use the "previous" option of scipy's interp1d function, but that does not work very good on not continuous data like the HATPRO flag, since missing (masked) values are filled with the minimum value before interpolation. This is not sensible for the flag data.
https://github.com/lacros-tropos/larda/blob/29b80f9d045736af26491d351f6bf1c7e73d6822/pyLARDA/Transformations.py#L159

Maybe you have a better idea of solving this with the current available functions?

**Comment by martin-rdz** [comment]
True point...
Could you think of a brief (<~40 lines) example for the [how to use section of the documentation](https://lacros-tropos.github.io/larda-doc/html/how_to_use.html)?

**Comment by jroettenbacher** [comment]
Sure can do. Should I just send it to you? Or can I add it as a pull request somewhere?

**Pull request merged**
